name: Build UABEA Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet publish UABEAvalonia/UABEAvalonia.csproj -c Release -r linux-arm64 --self-contained true -o ./publish
    
    - name: Fix libonigwrap directory
      run: find UABEAvalonia/bin/Release/net8.0/ -name libonigwrap.so -type f -exec cp {} ./publish \;
    
    - name: Remove unused platforms
      run: |
        if [ -d "UABEAvalonia/bin/Release/net8.0/linux-arm64" ]; then
          cp -r UABEAvalonia/bin/Release/net8.0/linux-arm64 ./publish
        else
          ls UABEAvalonia/bin/Release/net8.0/
        fi
      
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: uabea-ubuntu
        path: ./publish
